((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 72)
         (cmake-ide-project-dir . "/home/vagrant/anyun/storage_gateway3/src")
         (cmake-ide-build-dir .   "/home/vagrant/anyun/storage_gateway3/src")))
 (c-mode . ((c-file-style . "stroustrup")
            (subdirs . nil))))
